name: Test Python Package

on:
  pull_request:
  push:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (KERN-9 + CARTA)
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common gnupg
    
        # Add KERN-9 repo
        echo "deb-src http://ppa.launchpad.net/kernsuite/kern-9/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/kernsuite-ubuntu-kern-9-focal.list
        sudo add-apt-repository -y ppa:kernsuite/kern-9
    
        # Add CARTA repo
        sudo add-apt-repository -y ppa:cartavis-team/carta
    
        # Update and install packages
        sudo apt-get update
        sudo apt-get install -y carta kernsuite

    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc g++ make \
          carta-backend carta-frontend casacore-dev casacore-data \
          python3-pip python3-virtualenv chromium-browser

    - name: Install, Run and Show executed notebook output
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install -U pip
        #python -m pip install --upgrade pip wheel "setuptools<68" maturin Cython numpy pyregion hatchling ipykernel meson-python
        python -m pip install git+https://github.com/ratt-ru/radiopadre-client.git@b1.2.3_updates
        python -m pip install --no-cache -e .
        python -m ipykernel install --prefix=$(pwd)/venv --name=radiopadre --display-name "Radiopadre"
        jupyter kernelspec list
        run-radiopadre . --no-browser -V & 
        RADIOPID=$!
        sleep 5
        kill $RADIOPID 2>/dev/null || echo "Radiopadre exited early"
        run-radiopadre -V --nbconvert radiopadre-default.ipynb

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: radiopadre-test-results-py${{ matrix.python-version }}
        path: radiopadre-default.html
