name: Test Python Package

on:
  pull_request:
  push:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install, Run and Show executed notebook output
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install -U pip
        #python -m pip install --upgrade pip wheel "setuptools<68" maturin Cython numpy pyregion hatchling ipykernel meson-python
        python -m pip install git+https://github.com/ratt-ru/radiopadre-client.git@b1.2.3_updates
        python -m pip install --no-cache -e .
        python -m ipykernel install --prefix=$(pwd)/venv --name=radiopadre --display-name "Radiopadre"
        jupyter kernelspec list
        run-radiopadre . --no-browser -V & 
        RADIOPID=$!
        sleep 5
        kill $RADIOPID 2>/dev/null || echo "Radiopadre exited early"
        run-radiopadre -V --nbconvert radiopadre-default.ipynb

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: radiopadre-test-results-py${{ matrix.python-version }}
        path: radiopadre-default.html
